name: conda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - gym
  - gymnasium
  - stable-baselines3
  - matplotlib
  - pandas
  - pygame
  - cmake
  - make
  - clang
  - clangxx
  - libcxx
  - hackrf
  - pywavelets
  - gnuradio
  - pip
  - pip:
      - adafruit-circuitpython-mcp9808
      - adafruit-blinka
      - adafruit-platformdetect
      - gymnasium

# INSTALL DIREWCTLY ON JETSON:
# pip install cupy-cuda102